### ISSUE TITLE
error LNK2001: 无法解析的外部符号 _OrtGetApiBase@0

### ISSUE THREAD

**Issue by Eunsolfs** [sml2h3/onnxruntime-static-lib#1]
大佬你好，我在调用您的onnxruntime 静态库时，发现编译时出现以下错误提示：
include路径 lib路径，以及需要附加的lib完全参考readme写的，请问我应该怎么解决这个问题呢？还请大佬赐教

`1>OcrUtils.obj : error LNK2001: 无法解析的外部符号 _OrtGetApiBase@0
1>main.obj : error LNK2001: 无法解析的外部符号 _OrtGetApiBase@0
1>moc_ocr.obj : error LNK2001: 无法解析的外部符号 _OrtGetApiBase@0
1>moc_OcrLite.obj : error LNK2001: 无法解析的外部符号 _OrtGetApiBase@0
1>AngleNet.obj : error LNK2001: 无法解析的外部符号 _OrtGetApiBase@0
1>CrnnNet.obj : error LNK2001: 无法解析的外部符号 _OrtGetApiBase@0
1>DbNet.obj : error LNK2001: 无法解析的外部符号 _OrtGetApiBase@0
1>OcrLite.obj : error LNK2001: 无法解析的外部符号 _OrtGetApiBase@0`

**Comment by sml2h3** [comment]
这个报错属实没看出来问题在哪

**Comment by Eunsolfs** [comment]
> 这个报错属实没看出来问题在哪

感谢大佬编译的opencv static / onnxruntime static, 总算是把DdddOcr项目编译过了

**Comment by Eunsolfs** [comment]
大佬  我发现您发布的这份onnxrumtime static 是x64版本的 ，请问有x86的版本么？如果有的话能否再发布一份release。感谢

**Comment by Eunsolfs** [comment]
或者onnxruntime static 是需要怎样的编译指令来编译呢？我已经通过git clone --recurse 拉取了完整的onnxruntime代码, 请问下怎么编译static的库, 这样我就可以自己来尝试下了

**Comment by sylarrrm** [comment]
> > 这个报错属实没看出来问题在哪
> 
> 感谢大佬编译的opencv static / onnxruntime static, 总算是把DdddOcr项目编译过了
大佬 我出现了和你这个一样的错误 你是咋解决的
